name: Build and Push Images
on:
  push:
    branches:
      - master
    tags:
      - 'v*'

jobs:
  push-image-to-docker-hub:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: tryoo0607/probe-test
          tags: |
            # 브랜치 빌드 → :master 같은 태그
            type=ref,event=branch

            # 태그 빌드(예: v1.2.3) → semver 태그 세트
            type=semver,pattern={{version}},value={{tag}}
            type=semver,pattern={{major}}.{{minor}},value={{tag}}
            type=semver,pattern={{major}},value={{tag}}

            # 기본 브랜치(master)일 때만 latest 부여(선택)
            type=raw,value=latest,enable={{is_default_branch}}
      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: index.docker.io/tryoo0607/probe-test
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true